version: "3.7"
services:
  spark-master:
    image: spark-master:2.4.6
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
       #- /mnt/spark-apps:/opt/spark-apps
       #- /mnt/spark-data:/opt/spark-data
       - /media/larissacsh/Data/DemoGraphs:/DemoGraphs
       - /media/larissacsh/Data/configuration:/Config
    environment:
      - "SPARK_LOCAL_IP=spark-master"
  spark-worker-1:
    image: spark-worker:2.4.6
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.3
    volumes:
       #- /mnt/spark-apps:/opt/spark-apps
       #- /mnt/spark-data:/opt/spark-data
       - /media/larissacsh/Data/DemoGraphs:/DemoGraphs
       - /media/larissacsh/Data/configuration:/Config
  spark-submit:
    container_name: spark-submit
    image: spark-submit:2.4.6
    hostname: spark-submit
    ports:
      - "6080:6080"
    depends_on:
      - spark-master
    environment:
      - "SPARK_LOCAL_IP=spark-submit"
    networks:
      spark-network:
        ipv4_address: 10.5.0.6
    volumes:
       #- /mnt/spark-apps:/opt/spark-apps
       #- /mnt/spark-data:/opt/spark-data
       - /media/larissacsh/Data/DemoGraphs:/DemoGraphs
       - /media/larissacsh/Data/configuration:/Config
networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
